### ISSUE TITLE
Request: Support filtering/querying plugin dependencies too

### ISSUE THREAD

**Issue by philroche** [maxgio92/pomscan#3]
Related to https://github.com/maxgio92/pomscan/issues/2 It would be very helpful to be able to query plugins defined in a pom.xml

**Comment by maxgio92** [comment]
Thank you @philroche for checking that. I totally agree

**Comment by maxgio92** [comment]
I propose a separated command for plugins, considering that they're not runtime dependencies of a project. In turn, they could have dependencies, still, they're build time dependencies.

For that reason, I would integrate the support and made it available through a dedicated command. Something like:

```shell
pomscan plugin --artifact-id|-a [--group-id|-g] [PROJECT_PATH] [--version-only]
```

**Comment by maxgio92** [comment]
Hi @philroche, the tool now with version v0.3.0 is able to search:
* plugins
* plugin dependencies

Regarding your request, the following is an example to search `ant-contrib` built time dependency across plugins, running `pomscan` from the source repository directory:

```shell
$ pomscan dependency --plugin -a ant-contrib -p pkg/project/testdata/plugin-dependency
📦 ant-contrib.ant-contrib
artifact-id : ant-contrib
group-id : ant-contrib
pom-file : pkg/project/testdata/plugin-dependency/pom.xml
version : ${ant.contrib.version}
version-property-name : ant.contrib.version
version-property-value : 1.0b3
version-property-declare-path : pkg/project/testdata/plugin-dependency/pom.xml
```

You can find CLI reference here: [Pomscan CLI reference](https://github.com/maxgio92/pomscan/blob/main/docs/_index.md)

Also, if you want to feed the result to Pombump to create patches, you can find an example here: [Usage with bumps](https://github.com/maxgio92/pomscan?tab=readme-ov-file#usage-with-bumps).

Let me know what do you think, and if this addresses your request :-)

**Comment by philroche** [comment]
@maxgio92 Thank you. Taking jenkins as an example @ https://github.com/jenkinsci/jenkins/blob/jenkins-2.452.4/pom.xml. I'd like to be able to search for the `maven-compiler-plugin` artifact which I know exists @ https://github.com/jenkinsci/jenkins/blob/jenkins-2.452.4/pom.xml#L140 but currently with the v0.3.0 branch this is not finding the expected plugin.

```
➜  jenkins git:(jenkins-2.452.4) pomscan dependency --plugin --project-path . --artifact-id maven-compiler-plugin
Error: searching plugin build dependency: dependency not found
Usage:
  pomscan dependency [flags]

Aliases:
  dependency, dep

Flags:
  -a, --artifact-id string   Filter by artifact ID.
  -g, --group-id string      Filter by group ID. It must be combined with artifact ID.
  -h, --help                 help for dependency
      --plugin               Whether to search an artifact through the plugin build dependencies.
      --version-only         Print only matches that have the version set. It supports properties.

Global Flags:
      --debug                 Sets log level to debug
  -p, --project-path string   Project path (default ".")

error: searching plugin build dependency: dependency not found

```

Have I misunderstood the feature?

**Comment by maxgio92** [comment]
Hi @philroche, thanks for testing it!
Basically, for plugin there is a dedicated command: `pomscan plugin`.
For dependencies, whether built time (e.g. plugin's dependencies) or runtime dependencies, there's another dedicated command: `pomscan dependency|dep`.

So in your example, you should run:

```shell
$ pomscan plugin --project-path . --artifact-id maven-compiler-plugin
```

that would return
```shell
📦 org.apache.maven.plugins.maven-compiler-plugin
artifact-id : maven-compiler-plugin
group-id : org.apache.maven.plugins
pom-file : pom.xml

📦 org.apache.maven.plugins.maven-compiler-plugin
artifact-id : maven-compiler-plugin
group-id : org.apache.maven.plugins
pom-file : test/pom.xml

📦 .maven-compiler-plugin
artifact-id : maven-compiler-plugin
group-id :
pom-file : war/pom.xml
```

Any feedback is more than welcome! 😃

**Comment by philroche** [comment]
> pomscan plugin --project-path . --artifact-id maven-compiler-plugin

Excellent. That works.

How does that differ from the `pomscan dependency --plugin --project-path . --artifact-id maven-compiler-plugin` command though if it too is searching both build and runtime dependencies?

**Comment by maxgio92** [comment]
Thanks for the feedback @philroche.

So, the `dependency` command is to search dependencies. By default runtime dependencies are looked for, but with `--plugin` flag only dependencies of plugin, so build-time dependencies.

On the other side, plugins in POM are a different type of artifacts, to extend Maven functionalities, so that's why they have a dedicated command `plugin`.

I don't have a strong opinion here TBH, I've just ended up by following the POM models for artifacts.
I'm open to reconsider the UX :)

**Comment by philroche** [comment]
Thank you for the explanation. No need to change, I just didn't know enough to understand the difference.

**Comment by maxgio92** [comment]
Thanks for the feeedback. If you agree I'm going to close this issue as completed @philroche :)

**Comment by philroche** [comment]
+1
